from .reversiblecsv import ReversibleCSVData


class GDAXCSVData(ReversibleCSVData):
    """
    Parse GDAX CSV data generated by the GDAX scraper

    Default parameters are configured to the GDAX CSV format.
    """

    params = (
        ('headers', False),
        ('open', 3),
        ('high', 2),
        ('low', 1),
        ('close', 4),
        ('volume', 5),
        ('openinterest', -1),
        ('reverse', True),
    )
